app:
  name: "reverse_seat"
  mode: "dev"
  port: 8080

mysql:
  path: '110.40.228.197'
  port: '3308'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'seat'
  username: 'root'
  password: '3yueruanjian!'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

zap:
  level: 'info'
  format: 'console'
  prefix: '[seat]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true
  file-path: "./log/logfile.log"

redis:
  db: 3
  addr: '110.40.228.197:6379'
  password: ''

jwt:
  signing-key: "seat"
  expires: 168
  buffer: 24
  issuer: "seat-team"



