mysql:
  path: '127.0.0.1'
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'ass'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

zap:
  level: 'info'
  format: 'console'
  prefix: '[seat]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true
  file-path: "./log/logfile.log"

redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

jwt:
  signing-key: "seat"
  expires: 168
  issuer: "seat-team"



